spring:
  datasource:
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/cloudinary?serverTimezone=UTC&characterEncoding=UTF-8&sslMode=DISABLED&createDatabaseIfNotExist=true"
    username: "${DB_USER:root}"
    password: "${DB_PASSWORD:}"
    continueOnError: true
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    hikari:
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
      enabled: true

#Cloudinary Properties
cloudinary:
  cloud-name:
  api-key:
  api-secret:
